### ISSUE TITLE
Comment on specs paper line 39

### ISSUE THREAD

**Issue by mleair** [j3-fortran/generics#63]
https://github.com/j3-fortran/generics/blob/bd85929c6bd9995bed4d4150b92ae74f2ca04a3f/J3-Papers/Generics_Specs.txt#L39

Please provide some suggestive syntax for dummy parameter declaration.  There is no example of this until section M6 which is near the end of the document.

**Comment by mleair** [comment]
Alternatively, you could use a similar suggestive syntax in section B1 that you used for the RESTRICTION construct in F4.  You may want to make B1 and F4 similar for consistency.

**Comment by tclune** [comment]
I'm still very wary of exposing any suggested syntax for procedures and operators.       But I'll try to put something here.
