### ISSUE TITLE
Comment on line 165 in Specs paper

### ISSUE THREAD

**Issue by mleair** [j3-fortran/generics#65]
https://github.com/j3-fortran/generics/blob/bd85929c6bd9995bed4d4150b92ae74f2ca04a3f/J3-Papers/Generics_Specs.txt#L165

Is REQUIRES really a construct or is it a statement? I think of constructs as blocks of executable code such as the block statement, select case, select type, associate, etc  (see section 11.1 in the current Standard Draft).

**Comment by mleair** [comment]
I see you now call it a REQUIRES statement on line 172.  ;-)

**Comment by tclune** [comment]
Yes - I meant statement.  Thanks for catching this.
